export const main: string;
export const main_wrapper: string;
export const main_wrapper_form_container: string;
export const main_wrapper_form_container_login_form: string;
export const main_wrapper_form_container_login_form_text_section: string;
export const main_wrapper_form_container_text_block: string;
export const main_wrapper_header: string;
export const main_wrapper_header_link: string;
export const root: string;
